project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto  # re-render only when source changes

website:
  title: EDS 220 - Working with Environmental Datasets
  page-footer: 
    left: "This work is licensed under [Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0) License](https://creativecommons.org/licenses/by-nc/4.0/)" 

  announcement: 
    icon: hammer
    dismissable: true
    content: "This wesbite is under construction."
    type: primary
    position: below-navbar

  navbar:
    right:
      - text: home
        href: index.qmd
      - text: book
        href: book/preface.qmd  
      - text: discussion sections
        href: discussion-sections/discussion-sections-listing.qmd
      - text: assignments
        href: assignments/assignments-home.qmd             
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/carmengg/MEDS-eds-220-course 
          - text: Report a bug
            url: https://github.com/carmengg/MEDS-eds-220-course/issues
  sidebar:
    - id: book
      contents:
        - book/preface.qmd
        - book/chapters/lesson-0-create-conda-env.qmd
        - book/chapters/lesson-1-python-review.qmd
        - section: "Tabular Data"
          contents:
            - book/chapters/lesson-2-series-dataframes.qmd
            #- book/chapters/lesson-3-pandas-subsetting.qmd
            

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


bibliography: references/references.bib
csl: references/ieee-with-url.csl # citation style
