project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto  # re-render only when source changes

website:
  title: EDS 220 - Working with Environmental Datasets
  page-footer: 
    #background: dark
    left: "This work is licensed under [CC Attribution-NonCommercial 4.0 International (CC BY-NC 4.0) License](https://creativecommons.org/licenses/by-nc/4.0/)" 
    #left: <img src="index-images/bren-logo.png" alt="The Bren School of Environmental Science & Management logo" width="250"/>

    right: This website is built with [Quarto](https://quarto.org/) and [GitHub pages](https://github.com/MEDS-eds-220/MEDS-eds-220-course).

  announcement: 
    icon: hammer
    dismissable: true
    content: "This wesbite is under construction."
    type: primary
    position: below-navbar

  navbar:
    right:
      - text: home
        href: index.qmd
      - text: week by week
        href: week-by-week/week-by-week.qmd
      - text: notes
        href: book/preface.qmd  
      - text: discussion sections
        href: discussion-sections/discussion-sections-listing.qmd
      - text: assignments
        menu:
          - text: assignment 1 
            href: assignments/assignment1.qmd             
          - text: assignment 2
            href: assignments/assignment2.qmd                         
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/carmengg/MEDS-eds-220-course 
          - text: Report a bug
            url: https://github.com/carmengg/MEDS-eds-220-course/issues
  sidebar:
    - id: book
      contents:
        - book/preface.qmd
        #- book/setup.qmd
        - book/chapters/lesson-1-python-review.qmd
        - section: "Tabular data"
          contents:
            - book/chapters/lesson-2-series-dataframes.qmd
            - book/chapters/lesson-3-pandas-subsetting/lesson-3-pandas-subsetting.qmd
            - book/chapters/lesson-4-plotting-pandas.qmd
            - book/chapters/lesson-5-updating-dataframes.qmd
            - book/chapters/lesson-6-groupby.qmd
            - book/chapters/merging-data.qmd
            - book/chapters/lesson-7-time-series.qmd
        - section: "Vector data"
          contents:            
            - book/chapters/lesson-8-crs.qmd
            - book/chapters/lesson-9-vector-data.qmd
            - book/chapters/lesson-10-geopandas-intro/lesson-10-geopandas-intro.qmd
            - book/chapters/lesson-11-csv-to-geodataframe/lesson-11-csv-to-geo.qmd
        - section: "Appendices"
          contents:
            - book/appendices/comments-guidelines.qmd
            - book/appendices/A-python-environments.qmd
            

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


bibliography: references/references.bib
csl: references/ieee-with-url.csl # citation style

link-external-newwindow: True
 