# Week by week

You will find the course announcements and daily activities here. 

## Week 1 : Sept 30 - Oct 6

:::{.callout-note appearance="minimal" collapse="true" }
## What happened

### Class 1

1. [Course introduction slides](/slides/syllabus-slides.qmd)
2. Set up of GitHub repository for in-class coding sessions.
<!-- TODO: add fold-away with step-by-step instructions -->
3. Covered [Python review](/book/chapters/lesson-1-python-review.qmd) up to the end of the variables section.

::: {.callout-warning icon=false}
## Preparation for Wednesday class (October 2)
1. In your `EDS-220/eds220-2024-in-class` directory, create a new Python notebook called `week1-pandas-series.ipynb`.
2. **Read the notes chapter on [`pandas` series data frames](/book/chapters/lesson-2-series-dataframes.qmd) and follow along with the code.**
2. Solve the check-in exercises. We'll present these during class.
3. Make a summary of the lesson. What are the most important concepts or ideas?
:::


### Class 2

1. Finished [Python review](/book/chapters/lesson-1-python-review.qmd).
2. Student presentations of [`pandas.Series` and `pandas.DataFrames`](/book/chapters/lesson-2-series-dataframes.qmd) exercises

### Discussion section

There's no setup for this week's discussion section. We'll follow the materials in [Discussion Section 1.](/discussion-sections/ds1-prelim-data-exploration.qmd)
:::

## Week 2 : Oct 7 - Oct 13

:::{.callout-note appearance="minimal" collapse="true" }
## What happened

### Class 3

1. Completed the following activity to add the `data/` directory to the `.gitignore` file of the `EDS-220/in-class-notebooks/` directory.

::: {.callout-tip collapse="true" icon=false}
## Edit .gitignore file through terminal
## Setup:
1. Download the CSV file `wetlands_seasonal_bird_diversity.csv` from our [shared drive](https://drive.google.com/file/d/1VCmBYZ1LmgmvxQt9KEcczc6KPDlAYRp0/view?usp=share_link).

2. In the workbench 1 server, inside your `EDS-220/in-class-notebooks/` directory, create a new directory called `data`. 

3. Using the file navigation panel, upload the `wetlands_seasonal_bird_diversity.csv` file to the `data/` directory. 

## In the terminal:

1. Verify you are in the `in-class-notebooks/` directory by using `pwd`. Your output should look like this:
```default
/Users/your-username/MEDS/EDS-220/in-class-notebooks
```

2. Run `git status`. At the end of the output you'll see:
```default
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        data/
```
This means git knows the `data/` directory exists and we have the risk of adding it to a commit.

3. Run `ls` to see the files in the directory. Your output will look like this, notice the `.gitiginore` file is not listed:
```default
README.md  week1-lesson1-python-review.ipynb
data       week1-lesson3-pandas-subsetting.ipynb
```

4. Run `ls -a` to see *all* files in the directory, including hidden files (those that start with a period `.`). At this point, your output will look like this:
```default
.                   README.md
..                  data
.git                week1-lesson1-python-review.ipynb
.gitignore          week1-lesson3-pandas-subsetting.ipynb
.ipynb_checkpoints
```

4. Run `nano .gitignore`. This will open the `.gitignore` file in the `nano` editor.

5. Add the `data/` folder to the `.gitignore` file by adding this text at the top of the file:
```default
# Ignore the 'data' directory
data/
```

5. Once you have made your changes, save the file:
 - In `nano`, press `CTRL + O` (the letter O, not zero) to save.
 - Press `Enter` to confirm the file name (`.gitignore`).

6. Exit the editor by pressing `CTRL + X`.

7. Run `less .gitignore` to scroll through the `.gitignore` file and verify the changes are there. 
- Use the arrow keys or `Page Up`/`Page Down` to scroll through the file.
- Press `q` to exit. 

8. Run `git status` and check the output. The `data/` directroy will no longer be listed!

9. Commit and push your changes to the `.gitignore`.
:::

3. Covered [`pandas` subsetting notes](/book/chapters/lesson-3-pandas-subsetting/lesson-3-pandas-subsetting.qmd) up to selecting rows using a condition.

::: {.callout-warning icon=false}
## Preparation for Wednesday class (October 9)
1. In your `EDS-220/eds220-2024-in-class` directory, create a new Python notebook called `week2-basic-plotting.ipynb`.
2. **Read the notes on [basic plotting](/book/chapters/lesson-4-plotting-pandas.qmd) up to and including the "updating the index" section and follow along with the code.**
2. Solve the check-in exercises. We'll present these during class.
3. Make a summary of this part of the lesson. What are the most important concepts or ideas?
:::


### Class 4

1. Finished [`pandas` subsetting notes](/book/chapters/lesson-3-pandas-subsetting/lesson-3-pandas-subsetting.qmd).
2. Student presentations of [basic plotting](/book/chapters/lesson-4-plotting-pandas.qmd) exercises
3. Covered [basic plotting](/book/chapters/lesson-4-plotting-pandas.qmd) up to scatter plots. The last two sections, about bar plots and histograms were assigned as reading. 

### Discussion section

::: {.callout-warning icon=false}
Complete steps 1,2 and 3 of the [second discussion section](/discussion-sections/ds-2-water-crisis-exploration.qmd) to load the data before the discussion section.
You’ll be working on exercises 4-9 during section, so it is important that you have the data ready to go tomorrow.

Check-in with your discussion section teams via Slack just to make sure you’re all ready! :raised_hands:
:::

### Homework announcements
::: {.callout-important icon=false}
## Rename homework notebooks before uploading them to Gradescope
For your [upcoming assignment submission](/assignments/assignment1.qmd), you’ll be downloading your notebooks and then uploading them to Gradescope. Before you upload your finished notebooks to Gradescope, **please rename your notebooks** so they are called

- `hwk1-task2-corals-YOURLASTNAME.ipynb` and 
- `hwk1-task3-earthquakes-YOURLASTNAME.ipynb.` 

It’s important to do this so we can keep track of resubmissions. 

Thanks!
:::

::: {.callout-warning icon=false} 
## Updates to Gradescope's autograder
Here’s updates about how auto-grading will work in this first assignment:

- **If you want to know your autograder score at any point**, you may upload your notebook to the `Homework 1 Task 2 - AUTOGRADER CHECK ONLY` or `Homework 1 Task 3 - AUTOGRADER CHECK ONLY` assignments on gradescope.
  - Once you submit your assignment,  you will be able to see your total score for the auto-grading, not the score for individual questions.
  - If you don’t have a 20/20 score in your auto-grade questions, it means there is some mistake with your code and you should go back and review it. If you can’t figure out where the issue is, discuss it with other people (first option always!), come see Annie or Carmen during OH, or use Slack.

- The `AUTOGRADER CHECK ONLY` assignments on gradescope are strictly for you to see how you did on the assignment. We will not be using these grades at all
- You must still submit your final assignment to the `Homework 1- Task 2 - Corals` and `Homework 1 - Task 3 - Earthquakes` assignment
- Make sure you’re keeping up with your classmate’s questions and answers on Slack.
- When submitting your final notebook, please make sure to follow the instructions above regarding how to name the notebook

Thanks for your patience as we work through these initial Autograder kinks! 
:::
:::

## Week 3 : Oct 14 - Oct 20

:::{.callout-note appearance="minimal" collapse="true" }
## What happened
### Class 5

1. Covered [updating dataframes](/book/chapters/lesson-5-updating-dataframes.qmd) up to first example of `SettingWithCopyWarning`.


::: {.callout-warning icon=false}
## Preparation for Wednesday class (October 16)
1. In your `EDS-220/eds220-2024-in-class` directory, create a new Python notebook called `week3-groupby.ipynb`.
2. **Read the notes chapter on [grouping](/book/chapters/lesson-6-groupby.qmd) and follow along with the code.**
3. Summarize the lesson and solve the check-in exercise. We'll present these during class.
:::

### Class 6

1. Finished [updating dataframes](/book/chapters/lesson-5-updating-dataframes.qmd) notes. 

2. Went over how to update the message in the last commit **when it hasn't been pushed yet** using 
```default
git commit --amend -m "NEW MESSAGE"
```

3. Discussion of [grouping notes](/book/chapters/lesson-6-groupby.qmd) by students. 

4. Covered [conda environments notes](/book/appendices/A-python-environments.qmd) up to exercise 7.

### Discussion section

::: {.callout-warning icon=false}
## Load data before section
Complete steps 1,2 and 3 of the [third discussion section](/discussion-sections/ds3-hares.qmd) to load the data before the discussion section.
You’ll be working on exercises 4-8 during section, so it is important that you have the data ready to go tomorrow.

Check-in with your discussion section teams via Slack just to make sure you’re all ready! 
:::
:::

## Week 4 : Oct 21 - Oct 27
:::{.callout-note appearance="minimal" collapse="true" }
## What happened

### Class 7

1. Built [conda environment](/book/appendices/A-python-environments.qmd) for the course.
 
::: {.callout-tip icon=false collapse="true" }
## How to build the conda environment for the course in your computer
  1. Open VSCode on your computer.

  2. Clone your `eds220-2024-in-class` GitHub repository. You can do it using the command palette. 

  3. Download the following YAML file and move it to the top of your `eds220-2024-in-class` local directory:
    [https://github.com/MEDS-eds-220/MEDS-eds-220-course/blob/main/eds-220-env.yml]()

  4. Open a terminal inside VSCode and in it:

  a. Verify you are in the `eds220-2024-in-class` directory. 
  b. Verify that the `eds-220-env.yml` file is in the directory.
  c. Run the following conda command to build the environment used for the course:
  ```default
  conda env create --name eds220-env --file eds-220-env.yml
  ```
    
It will take about 10 minutes to build the environment. Once conda has finished, verify that the environment is listed. Inside VSCode, you'll be able to select the `eds220-env` kernel to run your notebooks.  
:::

2. Covered [time series notes](/book/chapters/lesson-7-time-series.qmd).

::: {.callout-warning icon=false}
## Preparation for Wednesday class (October 23)
Read the notes on [coordinate reference systems](/book/chapters/lesson-8-crs.qmd) and [vector data formats](/book/chapters/lesson-9-vector-data.qmd). Most of it should be reciew from EDS 223. We will have some questions to test your understanding of key concepts at the start of the next class. 
:::

### Class 8

Covered [`geopandas` notes](/book/chapters/lesson-10-geopandas-intro/lesson-10-geopandas-intro.qmd).

### Discussion section

No work to do ahead of the discussion section. 
:::

## Week 5 : Oct 28 - Nov 3

::: {.callout-warning icon=false}
## Preparation for Wednesday class (October 30)
1. Read notes on [data merging](/book/chapters/merging-data.qmd)
2. Delete previous `eds220-env` conda environment in your local computer.
3. Create a new one using this [YAML file](https://github.com/MEDS-eds-220/MEDS-eds-220-course/blob/main/eds-220-env.yml), name it `eds220-env` (that's why you shoul delete the old one).
:::