# Week 1 : {{< var week1-range >}}

## Class 2 ({{< var week1-tuesday >}})

1. Student presentations of [`pandas.Series` and `pandas.DataFrames`](/book/chapters/lesson-2-series-dataframes.qmd) exercises.
2. Created a directory called `data` within the `eds220-in-class` repository  (in workbench-1) and added it to `.gitignore` via GitHub.
2. Download the CSV file `wetlands_seasonal_bird_diversity.csv` from our [shared drive]({{< var shared-data-folder >}}) and uploaded it to the `data/` folder.
3. Covered the [`pandas` subsetting notes](/book/chapters/lesson-3-pandas-subsetting/) up to selecting a single column. We started from a [pre-filled notebook available here]({{< var shared-notebooks-folder >}}).

::: {.callout-warning icon=false}
## Preparation for next class ({{< var week1-thursday >}})
1. In your `EDS-220/eds220-in-class` directory, create a new Python notebook called `week1-basic-plotting.ipynb`.
2. **Read the notes on [basic plotting](/book/chapters/lesson-4-plotting-pandas.qmd) and follow along with the code in the `week1-basic-plotting.ipynb` notebook.**
3. Solve the check-in exercises in the `week1-basic-plotting.ipynb`. We'll present these during class.
4. Make a summary of the lesson. What are the most important concepts or ideas?
:::


<br>


## Class 3 ({{< var week1-thursday >}})

1. Finished [`pandas` subsetting notes](/book/chapters/lesson-3-pandas-subsetting/lesson-3-pandas-subsetting.qmd).
2. Student presentations of [basic plotting](/book/chapters/lesson-4-plotting-pandas.qmd) exercises.

::: {.callout-warning icon=false}
## Preparation for next class ({{< var week2-tuesday >}})

**Task 1**

1. In your `EDS-220/eds220-in-class` directory, create a new Python notebook called `week2-groupby.ipynb`.
2. **Read the notes on [grouping](/book/chapters/lesson-6-groupby.qmd) and follow along with the code `week2-groupby.ipynb` notebook.** 
3. Summarize the lesson and solve the check-in exercises. We'll present them during class.

**Task 2**

1. In your `EDS-220/eds220-in-class` directory, create a new Python notebook called `week2-updating-dataframes.ipynb`.
2. **Read the notes on [updating dataframes](/book/chapters/lesson-5-updating-dataframes.qmd) up to the end of the "Removing columns" section and follow along with the code in the `week2-updating-dataframes.ipynb` notebook.** 
3. We will cover the "Updating values" section during class. The class will start assuming you have all the data loaded. 
:::

::: {.callout-tip icon=false}
## Assignment 1 available this Friday

Assignment 1 will be available by the end of tomorrow, {{< var hwk1-release >}} and will be due by 11:59 pm on {{< var hwk1-due >}}. 
:::

<br>

## Discussion section ({{< var week1-friday >}})

::: {.callout-warning icon=false}
## Preparation for discussion section

- Check who is your [assigned team]({{< var discussion-teams-spreadsheet >}}) for the EDS 220 discussion sections.

- Complete steps 1, 2, and 3 of the [first discussion section](/discussion-sections/ds1-prelim-data-exploration.qmd) to load and explore the data before the discussion section.

- You’ll be working on exercises 4-7 during section, so it is important that you have the data ready to go tomorrow.

- Check-in with your discussion section teams via Slack to make sure you’re all ready to go on Friday! 🙌
:::

<br>