# Week 2 : {{< var week2-range >}}

<!-- Planned (class calendar): Tuesday - Updating dataframes (Palmer penguins); grouping, merging, pivot | Thursday - Building conda environment; VS Code set up | Friday lab - Handling string data / CO river basin data -->

**THIS WEEK:** The schedule and rooms remain the same, but **the Thursday and Friday sessions will swap**. {{< var ta-name >}} will lead the discussion section on Thursday, and {{< var instructor-name >}} will lead the full class on Friday. Everyone is expected to attend both.


## Class 4 ({{< var week2-tuesday >}})

1. Fix `conda` path on the server:

a. Run 
```bash
/opt/miniforge3/bin/conda init bash
source ~/.bashrc
```

b. Run `conda info` to confirm. 

2. Review of [updating dataframes](/book/chapters/lesson-5-updating-dataframes.qmd) notes up to "Updating values" section.
3. Covered "Updating values" section of the [updating dataframes](/book/chapters/lesson-5-updating-dataframes.qmd) notes. 
4. Student presentations of [basic plotting](/book/chapters/lesson-4-plotting-pandas.qmd) and [grouping](/book/chapters/lesson-6-groupby.qmd) exercises.

::: {.callout-warning icon=false}
## Preparation for next class ({{< var week2-friday >}})

1. Install VS Code on your local computer. [MEDS installation guide](https://ucsb-meds.github.io/MEDS-installation-guide/#install-vscode)

2. Complete the [VSCode setup](/setup/setup-vscode.qmd). **Make sure to follow every step.**
:::

:::{.center-text}
**See the setup for the discussion section on Thursday below.**
:::

<br>


## Discussion section ({{< var week2-thursday >}})
::: {.callout-warning icon=false}
## Preparation for discussion section (on Thursday!)

- Complete steps 1, 2, and 3 of the [second discussion section](/discussion-sections/ds2-water-crisis-exploration.qmd) to load the data before the discussion section.

- You’ll be working on exercises 4-9 during section, so it is important that you have the data ready to go tomorrow.

- Check-in with your discussion section teams via Slack to make sure you’re all ready to go on Thursday! 🙌
:::

:::{.center-text}
**See the setup for the Friday lecture above.**
:::


<br>


## Class 5 ({{< var week2-friday >}})

1. Covered [conda environments notes](/book/appendices/A-python-environments.qmd) on the workbench and [slides](/slides/conda-environments-slides.qmd).
2. Set up VSCode and course environment to work on personal computers.

::: {.callout-warning icon=false}
## Preparation for next class ({{< var week3-tuesday >}})
*No set up for next class.*
:::

<br>

::: {.callout-important icon=false}
## Assignment 1 due this Saturday

[Assignment 1](/assignments/assignment1.qmd) is due by 11:59 pm on {{< var hwk1-due >}}.
:::