# Week 0 : {{< var week0-range >}}

<br>

**THIS WEEK ONLY:** The schedule and rooms remain the same, but {{< var ta-name >}} will lead the Thursday setup session, and {{< var instructor-name >}} will lead the full class on Friday. Everyone is expected to attend both.

### Assignments (due by the end of {{< var entry-survey-due >}})
 
1. **Read the course syllabus.** You will find it on the landing page for our [EDS 220 course website]({{< var course-website >}}).

2. **Complete the entry survey.** This will help the teaching team get to know you and your expectations for the course. The survey is part of your participation grade. [{{< var entry-survey >}}]({{< var entry-survey >}})

<br>

---

### Setup session ({{< var week0-thursday >}})

1. [Course logistics slides](/slides/syllabus-slides.qmd)
2. Setup of discussion sections repository following the [repository setup instructions](/discussion-sections/ds0-sections-setup.qmd)
3. Python assessment. This is not graded and completion counts towards participation grade. 

<br>

---

### Class 1 ({{< var week0-friday >}})


1. [Setup of GitHub repository for in-class coding sessions.](/setup/setup-in-class-repo.qmd)
3. Covered [Python review](/book/chapters/lesson-1-python-review.qmd). We started from a [pre-filled notebook available here]({{< var shared-notebooks-folder >}}).

At the end of the week your file structure should look like this:

```
EDS-220/
├── eds220-discussion-sections/
│   ├── README.md
│   ├── LICENSE
│   └── .gitignore
│
└── eds220-in-class/
    ├── README.md
    ├── LICENSE
    ├── .gitignore
    ├── data/
    └── week0-python-review.ipynb
```

::: {.callout-warning icon=false}
## Preparation for next class ({{< var week1-tuesday >}})

<!-- **Task 1** -->

1. In your `EDS-220/eds220-in-class` directory, create a new Python notebook called `week1-pandas-series.ipynb`.
2. **Read the notes chapter on [`pandas` series data frames](/book/chapters/lesson-2-series-dataframes.qmd) and follow along with the code in the `week1-pandas-series.ipynb` notebook.**
3. Solve the check-in exercises. We'll present these during class.
4. Make a summary of the lesson. What are the most important concepts or ideas?
5. **Read the [best practices to write comments](/book/appendices/comments-guidelines.qmd) in the notes.**

<!-- 
**Task 2**

THIS NEEDS TO BE ADDED NEXT YEAR

1. Create a directory called `data` within your `eds220-in-class` repository.
2. Download the CSV file `wetlands_seasonal_bird_diversity.csv` from our [shared drive](https://drive.google.com/drive/folders/1USqhiMLyN8GE05B8WJmHabviJGnmAsLP?usp=sharing).
3. **Do not push this file to GitHub.** 
-->
:::


