# Assignment 1

## Task 1: Datasheets for Datasets reading
So much goes into creating a dataset, and data is more than numbers and words in a file. Without a proper understanding of the whole context where data was created, biases, omissions, and inacuracies can go undetected. The [Datasheets for Datasets](https://doi.org/10.1145/3458723)  @datasheets-for-datasets advocates for transparency about the purpose and contents of datasets.

Check out this short interview with lead author Dr. Timnit Gebru on the motivation to write this article:
{{< video https://youtu.be/R7s7_T4yXak?si=08iVzefNwRlXVa95 >}}

**Read the paper and write a one-paragraph (between 100 and 150 words) open reflection about it.** You may use the following questions as prompts for your reflection, but feel free to discuss any topic in the article that caught your interest.

- How does a framework like the propsed “datasheets for datasets” can help transparency and accountability in data science? Is it feasable to implement it?

- Do you think there is a particular kind of data that may benefit the most from increased transparency about collection methods and processing methods? Why?


## Setup for tasks 2 and 3

:::{.callout-tip appearance="minimal"}

1. Fork this repository: https://github.com/carmengg/eds220-hwk-1

2. In the Taylor server, start a new JupyterLab session or access an active one.

3. Using the terminal, clone your `eds220-hwk-1` repository to a new directory under your `eds-220` directory.

4. In the terminal, use `cd` to navigate into the `eds-220-hwk-1` directory. Use `pwd` to verify `eds-220-hwk-1` is your current working directory.
:::

## Task 2: Exploring coral diversity data
For this task we are going to use data about Western Indian Ocean Coral Diversity @mcclanahan_western_2023 from the Knowledge Network for Biocomplexity (KNB) data repository.



Follow the instructions in the notebook `hwk1-task2.ipynb` to complete this task. In this task you will practice:

- preliminary data exploration
- accessing data using a URL from a data archive
- selecting data from a data frame
- basic git workflow
- commenting your