{
  "hash": "8e30b7e9437e4b7483d13d2df9d7813e",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Linear regression\n---\n\n\n\nIn this lesson we will learn how to perform a simple linear regression by examining the counts, weight, and size measurements of juvenile snowshoe hares (*Lepus americanus*) observed at the Bonanza Creek Experimental Forest from 1999 to 2012 @kielland_snowshoe_2017. \n\n<!--TODO: include learning objectives -->\n\n## About the data\n\nSize measurements, sex, and age of snowshoe hares were collected and made available by Dr. Knut Kielland and colleagues at the [Bonanza Creek Experimental Forest Long Term Ecological Research (LTER) site](https://www.lter.uaf.edu) located approximately 20 km southwest of Fairbanks, Alaska, USA. The data contains observations of 3380 snowshoe hares obtained by capture-recapture studies conducted yearly from 1999 to 2012 in three sampling sites: Bonanza Riparian, Bonanza Mature and Bonanza Black Spruce. \n\n![Photo credit: Jim Dau, [Alaska Department of Fish and Game.](https://www.adfg.alaska.gov/index.cfm?adfg=snowshoehare.main)](/book/images/lesson-18/snowshoehare_boards.jpg)\n\n## Data exploration\n\nLet's start by loading the data and taking a very high-level look at it:\n\n\n::: {#76af421a .cell execution_count=1}\n``` {.python .cell-code}\nimport os\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\nfrom sklearn.linear_model import LinearRegression\n```\n:::\n\n\n::: {#e4f066e9 .cell execution_count=2}\n``` {.python .cell-code}\nhares= pd.read_csv(os.path.join('data','knb-lter-bnz','55_Hare_Data_2012.txt'))\nhares.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>date</th>\n      <th>time</th>\n      <th>grid</th>\n      <th>trap</th>\n      <th>l_ear</th>\n      <th>r_ear</th>\n      <th>sex</th>\n      <th>age</th>\n      <th>weight</th>\n      <th>hindft</th>\n      <th>notes</th>\n      <th>b_key</th>\n      <th>session_id</th>\n      <th>study</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>11/26/1998</td>\n      <td>NaN</td>\n      <td>bonrip</td>\n      <td>1A</td>\n      <td>414D096A08</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>1370.0</td>\n      <td>160.0</td>\n      <td>NaN</td>\n      <td>917.0</td>\n      <td>51</td>\n      <td>Population</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>11/26/1998</td>\n      <td>NaN</td>\n      <td>bonrip</td>\n      <td>2C</td>\n      <td>414D320671</td>\n      <td>NaN</td>\n      <td>M</td>\n      <td>NaN</td>\n      <td>1430.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>936.0</td>\n      <td>51</td>\n      <td>Population</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>11/26/1998</td>\n      <td>NaN</td>\n      <td>bonrip</td>\n      <td>2D</td>\n      <td>414D103E3A</td>\n      <td>NaN</td>\n      <td>M</td>\n      <td>NaN</td>\n      <td>1430.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>921.0</td>\n      <td>51</td>\n      <td>Population</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>11/26/1998</td>\n      <td>NaN</td>\n      <td>bonrip</td>\n      <td>2E</td>\n      <td>414D262D43</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>1490.0</td>\n      <td>135.0</td>\n      <td>NaN</td>\n      <td>931.0</td>\n      <td>51</td>\n      <td>Population</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>11/26/1998</td>\n      <td>NaN</td>\n      <td>bonrip</td>\n      <td>3B</td>\n      <td>414D2B4B58</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>1710.0</td>\n      <td>150.0</td>\n      <td>NaN</td>\n      <td>933.0</td>\n      <td>51</td>\n      <td>Population</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#be953032 .cell execution_count=3}\n``` {.python .cell-code}\nhares.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 3380 entries, 0 to 3379\nData columns (total 14 columns):\n #   Column      Non-Null Count  Dtype  \n---  ------      --------------  -----  \n 0   date        3380 non-null   object \n 1   time        264 non-null    object \n 2   grid        3380 non-null   object \n 3   trap        3368 non-null   object \n 4   l_ear       3332 non-null   object \n 5   r_ear       3211 non-null   object \n 6   sex         3028 non-null   object \n 7   age         1269 non-null   object \n 8   weight      2845 non-null   float64\n 9   hindft      1633 non-null   float64\n 10  notes       243 non-null    object \n 11  b_key       3333 non-null   float64\n 12  session_id  3380 non-null   int64  \n 13  study       3217 non-null   object \ndtypes: float64(3), int64(1), object(10)\nmemory usage: 369.8+ KB\n```\n:::\n:::\n\n\nWe can see from the `info()` display that most of these variables are of type `object` (most likely `strings`) and some continuous and categorical numerical variables. To facilitate our data wrangling we convert the `date` column to a `datetime` type:\n\n::: {#e6e6b245 .cell execution_count=4}\n``` {.python .cell-code}\nhares['date'] = pd.to_datetime(hares['date'])\nprint(hares.date.dtype)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ndatetime64[ns]\n```\n:::\n:::\n\n\n## Examining hares age data\n\nFrom the data's `info()` display we can see that the `age` column has 1269 non-NA rows. In this example we are interested in working with data from juvenile hares exclusively. So we will:\n\n1. Examine the values in the `age` column\n2. Filter for observations in which age is 'adult' or 'juvenile'\n3. Investigate the age distributions across time\n\nFrom the [dataset's metadata](https://portal.edirepository.org/nis/metadataviewer?packageid=knb-lter-bnz.55.22) we know there are three allowedd values in the `age` column: \n\n- 'a' for 'adult', \n- 'j' for 'juvenile', and \n- 'm' for 'mortality'. \n\nLet's see the data in this column:\n\n::: {#474f5341 .cell execution_count=5}\n``` {.python .cell-code}\n# Examine unique values and counts in age column\npd.DataFrame(hares['age'].value_counts(dropna=False))\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>count</th>\n    </tr>\n    <tr>\n      <th>age</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>NaN</th>\n      <td>2111</td>\n    </tr>\n    <tr>\n      <th>A</th>\n      <td>564</td>\n    </tr>\n    <tr>\n      <th>J</th>\n      <td>267</td>\n    </tr>\n    <tr>\n      <th>a</th>\n      <td>183</td>\n    </tr>\n    <tr>\n      <th>j</th>\n      <td>128</td>\n    </tr>\n    <tr>\n      <th>1/2/2013</th>\n      <td>21</td>\n    </tr>\n    <tr>\n      <th>1/4/2013</th>\n      <td>21</td>\n    </tr>\n    <tr>\n      <th>3/4/2013</th>\n      <td>18</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>U</th>\n      <td>11</td>\n    </tr>\n    <tr>\n      <th>?</th>\n      <td>10</td>\n    </tr>\n    <tr>\n      <th>a 3/4 yr.</th>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>2 yrs.</th>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>u</th>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>A 3/4</th>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>1.5</th>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>3.5 yrs.</th>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>2.25 yrs</th>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>1 yr.</th>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>1 yr</th>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>a 1 yr.</th>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>A 1.5</th>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>2.5 yrs</th>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>3 yrs.</th>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>a 2 yrs.</th>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>J 3/4</th>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>2 yrs</th>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>A 1/2</th>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>a 1 yr</th>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>1.25</th>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>3.25 yrs.</th>\n      <td>1</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n<br>\n\nThis is the time to make a decision: since the metadata states that 'a' indicates adult and 'j' indicates juvenile, we will only keep observations that have 'a' or 'j' (either capitalized or not) as part of the age value. \n\n::: {#3424efc0 .cell execution_count=6}\n``` {.python .cell-code}\n# Update age values to juvenile and adult for observations where 'a' and 'j' are included\nhares.loc[hares.age.str.contains('j', case=False, na=False), 'age'] = 'juvenile'\nhares.loc[hares.age.str.contains('a', case=False, na=False), 'age'] = 'adult'\n\n# Filter for confirmed observations of juvenile and adult hares\nhares_juv_adult = hares[hares.age.isin(['juvenile', 'adult'])].copy()\nprint(f\"Number of selected juvenile and adult hares: {len(hares_juv_adult)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNumber of selected juvenile and adult hares: 1155\n```\n:::\n:::\n\n\nTo better understand our data we examine the distribution of hare age across years. Let's wrangle our data a bit to get there:\n\n::: {#9e82f95b .cell execution_count=7}\n``` {.python .cell-code}\n# Extract year in which each observation happened\nhares_juv_adult['year'] = hares_juv_adult.date.dt.year\n\n# Create hares/year dataframe\nhares_per_year = (hares_juv_adult.groupby(['year','age']).size()   # Note: size() counts all elements, including NAs\n                                 .reset_index(name='counts')       # Remove multi-index\n                                 .pivot(index='year', columns='age', values='counts')   # Pivot into long format\n                                 )\nhares_per_year\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>age</th>\n      <th>adult</th>\n      <th>juvenile</th>\n    </tr>\n    <tr>\n      <th>year</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1999</th>\n      <td>150.0</td>\n      <td>126.0</td>\n    </tr>\n    <tr>\n      <th>2000</th>\n      <td>159.0</td>\n      <td>67.0</td>\n    </tr>\n    <tr>\n      <th>2001</th>\n      <td>72.0</td>\n      <td>22.0</td>\n    </tr>\n    <tr>\n      <th>2002</th>\n      <td>3.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>2003</th>\n      <td>1.0</td>\n      <td>18.0</td>\n    </tr>\n    <tr>\n      <th>2004</th>\n      <td>NaN</td>\n      <td>8.0</td>\n    </tr>\n    <tr>\n      <th>2005</th>\n      <td>95.0</td>\n      <td>48.0</td>\n    </tr>\n    <tr>\n      <th>2006</th>\n      <td>101.0</td>\n      <td>15.0</td>\n    </tr>\n    <tr>\n      <th>2007</th>\n      <td>13.0</td>\n      <td>5.0</td>\n    </tr>\n    <tr>\n      <th>2008</th>\n      <td>84.0</td>\n      <td>57.0</td>\n    </tr>\n    <tr>\n      <th>2009</th>\n      <td>10.0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>2010</th>\n      <td>21.0</td>\n      <td>3.0</td>\n    </tr>\n    <tr>\n      <th>2011</th>\n      <td>45.0</td>\n      <td>20.0</td>\n    </tr>\n    <tr>\n      <th>2012</th>\n      <td>5.0</td>\n      <td>6.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nIf  you are wondering, here `year` is the name of the dataframe's row index and `age` is the name of the column index. \nIn this format it is easy to create a stacked bar plot to examine the occurrence of juvenile and adult hares:\n\n::: {#c9de00df .cell execution_count=8}\n``` {.python .cell-code code-fold=\"true\"}\n# Create figure + axes\nfig, ax = plt.subplots(figsize=(8, 5))\n\nhares_per_year[['juvenile', 'adult']].plot(    # Rearrange columns for stacking order\n    kind='bar',\n    stacked=True,\n    ax=ax,\n    edgecolor='black',\n    color=[\"#8FBC8F\", \"#4682B4\"], \n)\n\n# Labels, title, and legend\nax.set_xlabel(\"Year\")\nax.set_ylabel(\"Count\")\nax.set_title(\"Juvenile and Adult Snowshoe Hares per Year \\n at Bonanza Creek Experimental Forest (1999-2012)\",\n             {'fontsize':15})\nax.legend(title=\"Age class\",\n         loc=\"upper right\",   \n         bbox_to_anchor=(0.9, 0.9))\n\n# Axes and ticks\nax.spines['top'].set_visible(False)\nax.spines['right'].set_visible(False)\nplt.xticks(rotation=45)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](lesson-18-linear-regression_files/figure-html/cell-9-output-1.png){}\n:::\n:::\n\n\nNo observations of juvenile snowshoe hares were made during 2002, while the highest count was registered in 1999 (the first year of the study) with 126 observations. In the previous plot we can see a diminishing trend in the number of juvenile hare trappings. The two exceptions are 2005, 2008, and 2011. \n\n<!-- In 2005 juvenile hare counts were 6 times higher than in 2004, and in 2008 counts were 8.8 times higher than in 2007. In 2011 the juvenile snowshoe hare count was 9.5 times higher than in 2010. -->\n\n:::{.callout-tip}\n# Exercise\nConsider the following question: In what ways could the data collection methods affect the results we see here?\n:::\n\n\n<!-- While these are absolute counts, these numbers are also impacted by effort. Moving forward I would suggest to conduct the trappings on the same dates every year and space these times across different seasons. For example the first two weeks of each month every year. I imagine juveniles are mostly present during Spring, but with climate change it is possible Spring weather does not come at the same dates in 2012 as in 1998, so there might be a risk of undercounting if the counts are done during a fixed period of time every year. I would also suggest to maintain the number and location of traps constant over the years. -->\n\n## Linear regression\n\nFor our analysis we want to investigate possible relations between hind foot length and weight for juvenile hares.\nLet's take a look at our target data:\n\n::: {#9524183a .cell execution_count=9}\n``` {.python .cell-code}\n# Subset juvenile hares with hind foot and weight measurements\njuveniles_weight_hindft = hares_juv_adult[(hares_juv_adult['hindft'].notna()) & \n                                          (hares_juv_adult['weight'].notna()) &\n                                          (hares_juv_adult['age']=='juvenile')]\n\n\nprint(f\"Number of juvenile hares with hind foot and weight measurements: {len(juveniles_weight_hindft)}\")\njuveniles_weight_hindft.plot.scatter(x='hindft', y='weight', alpha=0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNumber of juvenile hares with hind foot and weight measurements: 265\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](lesson-18-linear-regression_files/figure-html/cell-10-output-2.png){}\n:::\n:::\n\n\nWe can see there seems to be a linear trend between the weight and hind foout length variables, though as the hind foot length increases the variability does too. \n\nLet's investigate whether a linear model is an adequate way to describe this data. To do this we will use the [`LinearRegression`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html) model from the [`scikit-learn`](https://scikit-learn.org/stable/index.html) library. If you need a refresher about how a linear regression works, [click here](https://openintrostat.github.io/ims/model-slr.html) for a a great resource. \n\nThe trickiest part of fiting the model is to get the data in the required shape. From the [`LinearRegression` documentation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html) we see that:\n\n- input data (the x-values, independent variable, or training data) shape should be `(n_samples, 1)`. The 1 comes from having a single feature modeling the output data.\n- output data (the y-values, dependent variable, or target data) shape should be `(n_samples,)`.\n\nLet's select and reshape the input and output data accordingly:\n\n::: {#16260a6f .cell execution_count=10}\n``` {.python .cell-code}\n# x-values\nX = np.array(juveniles_weight_hindft['hindft']).reshape((-1, 1))   # Reshape to (n_samples, 1)\nprint(f\"Input data shape: {X.shape}\")\n\n# y-values\ny = np.array(juveniles_weight_hindft['weight'])    # Shape is (n_samples,)\nprint(f\"Output data shape: {y.shape}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nInput data shape: (265, 1)\nOutput data shape: (265,)\n```\n:::\n:::\n\n\nNext, we create a `LinearRegression` instance and fit it to our data to create a `model`. From the `model` we extract the coefficient of determination or $R^2$, and the x-axis intercept and slope from our linear model. \n\n::: {#9928cdfe .cell execution_count=11}\n``` {.python .cell-code}\n# Fit model\nmodel = LinearRegression().fit(X, y)\n\n# Calculate R^2\nR_sq = model.score(X, y)\nprint(f\"Coefficient of determination (R^2): {R_sq}\")\n\n# Retrieve intercept and slope\nintercept = model.intercept_\nprint(f\"x-axis intercept: {intercept}\")\n\nslope = model.coef_[0]\nprint(f\"Slope: {slope}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCoefficient of determination (R^2): 0.3871164783665736\nx-axis intercept: -352.77198564640594\nSlope: 10.092239638623006\n```\n:::\n:::\n\n\nRemember that the equation of the linear model is given by\n\n$$\\hat{y} = \\beta_0 + \\beta_1 x, $$\n\nwhere\n\n- $x$ = input variable\n- $\\hat{y}$ = **estimated $y$ value** at $x$ from the linear model \n- $\\beta_0$ = the **$x$-intercept** of the linear model, this is interpreted as the estimated average value when $x=0$\n- $\\beta_1$ = the **slope** of the linear model, this is the estimated difference in the predicted value $\\hat{y}$ per unit of $x$.\n\nThe **coefficient of determination**, $R^2$ is between 0 and 1, with $R^2=1$ describing a perfect fit of the model to the data. The $R^2$ value is interpreted as the amount of variation in the outcome variable $y$ that is explained by the least squares line the variable $x$. \n\n\nWe can use all this information to plot our linear model together with our data:\n\n::: {#a1eb624d .cell execution_count=12}\n``` {.python .cell-code code-fold=\"true\"}\nfig, ax = plt.subplots(figsize=(8,6))\n\nax.scatter(x=juveniles_weight_hindft['hindft'], \n           y=juveniles_weight_hindft['weight'], \n           alpha=0.5,\n           color='#8FBC8F')\n\n# Define parameters of the regression line\nx_start = juveniles_weight_hindft['hindft'].min()\nx_end = juveniles_weight_hindft['hindft'].max()\n\n# Plot the line\nax.plot([x_start, x_end], \n        [slope*x_start + intercept, slope*x_end + intercept],\n        color=\"darkred\", \n        lw=2, \n        linestyle=\"--\")\n\n# Add the parameters\nbeta0 = r'$intercept = \\hat\\beta_0 =$'+ str(round(intercept,2))\nax.text(80, 1300, beta0, fontsize=10, horizontalalignment='center')\n\nbeta1 = r'$slope = \\hat\\beta_1 =$' + str(round(slope,2))\nax.text(80, 1200, beta1, fontsize=10, horizontalalignment='center')\n\nr_squared = r'$R^2 =$' + str(round(R_sq,2))\nax.text(80, 1100, r_squared, fontsize=10, horizontalalignment='center')        \n\n# Add a title and axis label\nax.set_title('Relationship between hind foot length and weight of  \\n juvenile snowshoe hares at Bonanza Creek Experimental Forest',\n             {'fontsize':15})\nax.set_xlabel('Hind foot length (mm)')\nax.set_ylabel('Weight (g)')\n\n# Show the plot\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](lesson-18-linear-regression_files/figure-html/cell-13-output-1.png){}\n:::\n:::\n\n\n:::{.callout-tip}\n# Exercise\nAnswer the following questions:\n\na. Does it make sense to interpret the $x$-axis intercept as an estimated measurement of weight?\n\nb. What is the estimated change in weight for each millimiter increase in hind foot length?\n\nc. Does a linear model of weight with respect to hind foot length account completely for the change in the dependent variable? What other variables could be worth exploring to model the weight?\n\nd. How would you use the linear model to estimate the weight of a juvenile hare with hind foot length of 90 mm?\n:::\n\n<!--\n:::{.callout-tip}\n# Exercise 2\n\nThis would be an exercise about doing linear regression while grouping by sex\n:::\n-->\n\n",
    "supporting": [
      "lesson-18-linear-regression_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}