# About

**Welcome to the 'EDS 220 - Working with Environmental Datasets' course notes!**

Designed for the [UCSB Masters in Environmental Data Science (MEDS)](https://bren.ucsb.edu/masters-programs/master-environmental-data-science), this course will guide you through widely used environmental data formats and Python libraries for analyzing diverse environmental datasets.

The notes are organized following the increasing dimensions of different environmental datasets, from familiar tabular data to intricate multi-dimensional arrays. Through hands-on code and activities, you'll analyze real-world environmental datasets sourced from leading open data repositories and cloud platforms.

**Who is this course for?** 
EDS 220 is tailored for beginner Python programmers eager to deepen their skills. If you’re familiar with the basics of Python and have experience working in Jupyter notebooks, you're in the right place. 
You are also encouraged to bring along your git skills and GitHub profile, ready to practice the essential `git pull` - `git push` workflow as you progress.

Overall, these notes are just the beginning!
They offer a solid foundation but are, inevitably, a partial exposition of the incredibly vast ecosystem of data formats, repositories, and Python tools available in environmental data science. 
By the end of this course, you'll have a strong grasp of the fundamentals and also the confidence to dive deeper into using Python for environmental data science and continue your MEDS journey.

## Acknowledgements
A big thanks to the creators of the open-source Python libraries, datasets, and educational materials that have helped shape this course. Your contributions have made our learning journey richer and more impactful. Attribution is included in any materials where content is adapted from other resources.

## Contribute
📝 If you have suggestions on how to correct, improve, or expand these notes, please feel free to email Carmen Galaz García at galazgarcia@bren.ucsb.edu or [file a GitHub issue](https://github.com/MEDS-eds-220/MEDS-eds-220-course/issues). 

🌟 If these notes have been useful to you, consider adding a star to [the project's repository](https://github.com/MEDS-eds-220/MEDS-eds-220-course/)!

## Attribution

This work, including the course notes, discussion sections, and assignments, is licensed under [Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0) License](https://creativecommons.org/licenses/by-nc/4.0/). For attribution, please cite these materials as:

> C. Galaz García, EDS 220 - Working with Environmental Datasets, Course Notes. 2024. [Online]. Available: https://meds-eds-220.github.io/MEDS-eds-220-course/book/preface.html

or use the bib reference:

```bib
@misc{galaz_garcia_eds_2024,
	title = {EDS 220 - Working with Environmental Datasets, Course Notes},
	url = {https://meds-eds-220.github.io/MEDS-eds-220-course/book/preface.html},
	author = {Galaz García, Carmen},
	year = {2024},
}
```
