---
toc-title: ''
--- 
# Setup

## Software installation

All the course materials use the Python programming language and git for version control. To install or make sure you have these in your computer, follow the [MEDS Software Installation Guide](https://ucsb-meds.github.io/MEDS-installation-guide/#check-git) from *4. Check for git* to *9. Install VS Code*. 


## Python environment
To install the libraries needed to execute the code in these notes you should create a conda environment using the `environment.yml` file in the [notes repository](https://github.com/MEDS-eds-220/MEDS-eds-220-course). 

**To build the environment:**

1. Download the `environment.yml` [file in the notes repository](https://github.com/carmengg/eds-220-book/blob/main/environment.yml). Place it in the directory where you will store the notebooks associated with these notes.

2. Using the terminal, navigate to the directory where the `environment.yml` file is.

3. Run the following command to build the environment:

```bash
conda env create -f environment.yml
```

4. Once the building finishes, run the following command to check the new environment was created:

```bash
conda env list
```
**To activate the environment:**

- In your terminal, ... **Finish**

- If you are using VSCode, you should be able open a Python notebok and select the new environment by accessing a drop-down list by clicking on the top right corner. 

**Add picture**

## Next
You're ready to start coding! The course starts with a Python review in the next section.